language: python

matrix:
    include:
        - os: linux
          sudo: required
          python: 3.6-dev
          env: TOXENV=py36
        - os: linux
          sudo: required
          python: 3.6
          env: TOXENV=py37
# command to install dependencies
install:
  - pip install -r requirements.txt
  - echo "Installation Done"
script:
  - echo "No tests yet"
