language: python

matrix:
    include:
        - os: linux
          sudo: required
          python: 3.2
          env: TOXENV=py32
        - os: linux
          sudo: required
          python: 3.3
          env: TOXENV=py33
        - os: osx
          language: generic
          env: TOXENV=py32
        - os: osx
          language: generic
          env: TOXENV=py33
# command to install dependencies
install:
  - pip install -r requirements.txt
  - echo "Installation Done"
script:
  - echo "No tests yet"
